import 'package:flutter/foundation.dart';
import 'dart:convert';
import 'package:iot_dashboard/model/iot_model.dart';

class IotController extends ChangeNotifier {
  List<IotItem> _items = [];

  List<IotItem> get items => _items;

  Future<void> fetchSampleIotItems() async {
    // 샘플 데이터 직접 포함 (혹은 따로 dart 파일로 분리 가능)
    final String jsonString = '''[
  {
    "id": "001",
    "type": "변위",
    "location": "Zone A-3",
    "status": "경고",
    "battery": "96%",
    "lastUpdated": "2025-01-20 14:30",
    "X(mm)": 0.12,
    "Y(mm)": -0.03,
    "Z(mm)": 0.04,
    "X_Deg" : 0,
    "Y_Deg" : 45,
    "Z_Deg" : 45,

    "batteryInfo": "양호",
    "download": "다운로드"
  },
  {
    "id": "002",
    "type": "변위",
    "location": "Zone A-3",
    "status": "경고",
    "battery": "96%",
    "lastUpdated": "2025-01-20 14:30",
    "X(mm)": 0.12,
    "Y(mm)": -0.03,
    "Z(mm)": 0.04,
    "X_Deg" : 0,
    "Y_Deg" : 45,
    "Z_Deg" : 45,

    "batteryInfo": "양호",
    "download": "다운로드"
  },
  {
    "id": "003",
    "type": "변위",
    "location": "Zone A-4",
    "status": "주의",
    "battery": "96%",
    "lastUpdated": "2025-01-20 14:30",
    "X(mm)": 0.12,
    "Y(mm)": -0.03,
    "Z(mm)": 0.04,
    "X_Deg" : 0,
    "Y_Deg" : 45,
    "Z_Deg" : 45,

    "batteryInfo": "양호",
    "download": "다운로드"
  },
  {
    "id": "004",
    "type": "변위",
    "location": "Zone A-1",
    "status": "정상",
    "battery": "96%",
    "lastUpdated": "2025-01-20 14:30",
    "X(mm)": 0.12,
    "Y(mm)": -0.03,
    "Z(mm)": 0.04,
    "X_Deg" : 0,
    "Y_Deg" : 45,
    "Z_Deg" : 45,

    "batteryInfo": "양호",
    "download": "다운로드"
  },
  {
    "id": "005",
    "type": "변위",
    "location": "Zone A-2",
    "status": "점검",
    "battery": "96%",
    "lastUpdated": "2025-01-20 14:30",
    "X(mm)": 0.12,
    "Y(mm)": -0.03,
    "Z(mm)": 0.04,
    "X_Deg" : 0,
    "Y_Deg" : 45,
    "Z_Deg" : 45,

    "batteryInfo": "양호",
    "download": "다운로드"
  },
  {
    "id": "006",
    "type": "변위",
    "location": "Zone A-1",
    "status": "경고",
    "battery": "96%",
    "lastUpdated": "2025-01-20 14:30",
    "X(mm)": 0.12,
    "Y(mm)": -0.03,
    "Z(mm)": 0.04,
    "X_Deg" : 0,
    "Y_Deg" : 45,
    "Z_Deg" : 45,

    "batteryInfo": "양호",
    "download": "다운로드"
  },
  {
    "id": "007",
    "type": "변위",
    "location": "Zone A-2",
    "status": "주의",
    "battery": "96%",
    "lastUpdated": "2025-01-20 14:30",
    "X(mm)": 0.12,
    "Y(mm)": -0.03,
    "Z(mm)": 0.04,
    "X_Deg" : 0,
    "Y_Deg" : 45,
    "Z_Deg" : 45,

    "batteryInfo": "양호",
    "download": "다운로드"
  },
  {
    "id": "008",
    "type": "변위",
    "location": "Zone A-4",
    "status": "점검",
    "battery": "96%",
    "lastUpdated": "2025-01-20 14:30",
    "X(mm)": 0.12,
    "Y(mm)": -0.03,
    "Z(mm)": 0.04,
    "X_Deg" : 0,
    "Y_Deg" : 45,
    "Z_Deg" : 45,

    "batteryInfo": "양호",
    "download": "다운로드"
  },
  {
    "id": "009",
    "type": "변위",
    "location": "Zone A-2",
    "status": "정상",
    "battery": "96%",
    "lastUpdated": "2025-01-20 14:30",
    "X(mm)": 0.12,
    "Y(mm)": -0.03,
    "Z(mm)": 0.04,
    "X_Deg" : 0,
    "Y_Deg" : 45,
    "Z_Deg" : 45,

    "batteryInfo": "양호",
    "download": "다운로드"
  },
  {
    "id": "010",
    "type": "변위",
    "location": "Zone A-2",
    "status": "경고",
    "battery": "96%",
    "lastUpdated": "2025-01-20 14:30",
    "X(mm)": 0.12,
    "Y(mm)": -0.03,
    "Z(mm)": 0.04,
    "X_Deg" : 0,
    "Y_Deg" : 45,
    "Z_Deg" : 45,

    "batteryInfo": "양호",
    "download": "다운로드"
  },
  {
    "id": "011",
    "type": "변위",
    "location": "Zone A-2",
    "status": "주의",
    "battery": "96%",
    "lastUpdated": "2025-01-20 14:30",
    "X(mm)": 0.12,
    "Y(mm)": -0.03,
    "Z(mm)": 0.04,
    "X_Deg" : 0,
    "Y_Deg" : 45,
    "Z_Deg" : 45,

    "batteryInfo": "양호",
    "download": "다운로드"
  },
  {
    "id": "012",
    "type": "변위",
    "location": "Zone A-3",
    "status": "점검",
    "battery": "96%",
    "lastUpdated": "2025-01-20 14:30",
    "X(mm)": 0.12,
    "Y(mm)": -0.03,
    "Z(mm)": 0.04,
    "X_Deg" : 0,
    "Y_Deg" : 45,
    "Z_Deg" : 45,

    "batteryInfo": "양호",
    "download": "다운로드"
  },
  {
    "id": "013",
    "type": "변위",
    "location": "Zone A-4",
    "status": "경고",
    "battery": "96%",
    "lastUpdated": "2025-01-20 14:30",
    "X(mm)": 0.12,
    "Y(mm)": -0.03,
    "Z(mm)": 0.04,
    "X_Deg" : 0,
    "Y_Deg" : 45,
    "Z_Deg" : 45,

    "batteryInfo": "양호",
    "download": "다운로드"
  },
  {
    "id": "014",
    "type": "변위",
    "location": "Zone A-4",
    "status": "정상",
    "battery": "96%",
    "lastUpdated": "2025-01-20 14:30",
    "X(mm)": 0.12,
    "Y(mm)": -0.03,
    "Z(mm)": 0.04,
    "X_Deg" : 0,
    "Y_Deg" : 45,
    "Z_Deg" : 45,

    "batteryInfo": "양호",
    "download": "다운로드"
  },
  {
    "id": "015",
    "type": "변위",
    "location": "Zone A-3",
    "status": "정상",
    "battery": "96%",
    "lastUpdated": "2025-01-20 14:30",
    "X(mm)": 0.12,
    "Y(mm)": -0.03,
    "Z(mm)": 0.04,
    "X_Deg" : 0,
    "Y_Deg" : 45,
    "Z_Deg" : 45,

    "batteryInfo": "양호",
    "download": "다운로드"
  },
  {
    "id": "016",
    "type": "변위",
    "location": "Zone A-3",
    "status": "점검",
    "battery": "96%",
    "lastUpdated": "2025-01-20 14:30",
    "X(mm)": 0.12,
    "Y(mm)": -0.03,
    "Z(mm)": 0.04,
    "X_Deg" : 0,
    "Y_Deg" : 45,
    "Z_Deg" : 45,

    "batteryInfo": "양호",
    "download": "다운로드"
  },
  {
    "id": "017",
    "type": "변위",
    "location": "Zone A-1",
    "status": "경고",
    "battery": "96%",
    "lastUpdated": "2025-01-20 14:30",
    "X(mm)": 0.12,
    "Y(mm)": -0.03,
    "Z(mm)": 0.04,
    "X_Deg" : 0,
    "Y_Deg" : 45,
    "Z_Deg" : 45,

    "batteryInfo": "양호",
    "download": "다운로드"
  },
  {
    "id": "018",
    "type": "변위",
    "location": "Zone A-4",
    "status": "주의",
    "battery": "96%",
    "lastUpdated": "2025-01-20 14:30",
    "X(mm)": 0.12,
    "Y(mm)": -0.03,
    "Z(mm)": 0.04,
    "X_Deg" : 0,
    "Y_Deg" : 45,
    "Z_Deg" : 45,

    "batteryInfo": "양호",
    "download": "다운로드"
  },
  {
    "id": "019",
    "type": "변위",
    "location": "Zone A-4",
    "status": "주의",
    "battery": "96%",
    "lastUpdated": "2025-01-20 14:30",
    "X(mm)": 0.12,
    "Y(mm)": -0.03,
    "Z(mm)": 0.04,
    "X_Deg" : 0,
    "Y_Deg" : 45,
    "Z_Deg" : 45,

    "batteryInfo": "양호",
    "download": "다운로드"
  },
  {
    "id": "020",
    "type": "변위",
    "location": "Zone A-3",
    "status": "경고",
    "battery": "96%",
    "lastUpdated": "2025-01-20 14:30",
    "X(mm)": 0.12,
    "Y(mm)": -0.03,
    "Z(mm)": 0.04,
    "X_Deg" : 0,
    "Y_Deg" : 45,
    "Z_Deg" : 45,

    "batteryInfo": "양호",
    "download": "다운로드"
  },
  {
    "id": "021",
    "type": "변위",
    "location": "Zone A-4",
    "status": "주의",
    "battery": "96%",
    "lastUpdated": "2025-01-20 14:30",
    "X(mm)": 0.12,
    "Y(mm)": -0.03,
    "Z(mm)": 0.04,
    "X_Deg" : 0,
    "Y_Deg" : 45,
    "Z_Deg" : 45,

    "batteryInfo": "양호",
    "download": "다운로드"
  },
  {
    "id": "022",
    "type": "변위",
    "location": "Zone A-3",
    "status": "주의",
    "battery": "96%",
    "lastUpdated": "2025-01-20 14:30",
    "X(mm)": 0.12,
    "Y(mm)": -0.03,
    "Z(mm)": 0.04,
    "X_Deg" : 0,
    "Y_Deg" : 45,
    "Z_Deg" : 45,

    "batteryInfo": "양호",
    "download": "다운로드"
  },
  {
    "id": "023",
    "type": "변위",
    "location": "Zone A-3",
    "status": "정상",
    "battery": "96%",
    "lastUpdated": "2025-01-20 14:30",
    "X(mm)": 0.12,
    "Y(mm)": -0.03,
    "Z(mm)": 0.04,
    "X_Deg" : 0,
    "Y_Deg" : 45,
    "Z_Deg" : 45,

    "batteryInfo": "양호",
    "download": "다운로드"
  },
  {
    "id": "024",
    "type": "변위",
    "location": "Zone A-2",
    "status": "경고",
    "battery": "96%",
    "lastUpdated": "2025-01-20 14:30",
    "X(mm)": 0.12,
    "Y(mm)": -0.03,
    "Z(mm)": 0.04,
    "X_Deg" : 0,
    "Y_Deg" : 45,
    "Z_Deg" : 45,

    "batteryInfo": "양호",
    "download": "다운로드"
  },
  {
    "id": "025",
    "type": "변위",
    "location": "Zone A-1",
    "status": "경고",
    "battery": "96%",
    "lastUpdated": "2025-01-20 14:30",
    "X(mm)": 0.12,
    "Y(mm)": -0.03,
    "Z(mm)": 0.04,
    "X_Deg" : 0,
    "Y_Deg" : 45,
    "Z_Deg" : 45,

    "batteryInfo": "양호",
    "download": "다운로드"
  },
  {
    "id": "026",
    "type": "변위",
    "location": "Zone A-2",
    "status": "점검",
    "battery": "96%",
    "lastUpdated": "2025-01-20 14:30",
    "X(mm)": 0.12,
    "Y(mm)": -0.03,
    "Z(mm)": 0.04,
    "X_Deg" : 0,
    "Y_Deg" : 45,
    "Z_Deg" : 45,

    "batteryInfo": "양호",
    "download": "다운로드"
  },
  {
    "id": "027",
    "type": "변위",
    "location": "Zone A-2",
    "status": "정상",
    "battery": "96%",
    "lastUpdated": "2025-01-20 14:30",
    "X(mm)": 0.12,
    "Y(mm)": -0.03,
    "Z(mm)": 0.04,
    "X_Deg" : 0,
    "Y_Deg" : 45,
    "Z_Deg" : 45,

    "batteryInfo": "양호",
    "download": "다운로드"
  },
  {
    "id": "028",
    "type": "변위",
    "location": "Zone A-3",
    "status": "경고",
    "battery": "96%",
    "lastUpdated": "2025-01-20 14:30",
    "X(mm)": 0.12,
    "Y(mm)": -0.03,
    "Z(mm)": 0.04,
    "X_Deg" : 0,
    "Y_Deg" : 45,
    "Z_Deg" : 45,

    "batteryInfo": "양호",
    "download": "다운로드"
  },
  {
    "id": "029",
    "type": "변위",
    "location": "Zone A-1",
    "status": "점검",
    "battery": "96%",
    "lastUpdated": "2025-01-20 14:30",
    "X(mm)": 0.12,
    "Y(mm)": -0.03,
    "Z(mm)": 0.04,
    "X_Deg" : 0,
    "Y_Deg" : 45,
    "Z_Deg" : 45,

    "batteryInfo": "양호",
    "download": "다운로드"
  },
  {
    "id": "030",
    "type": "변위",
    "location": "Zone A-1",
    "status": "주의",
    "battery": "96%",
    "lastUpdated": "2025-01-20 14:30",
    "X(mm)": 0.12,
    "Y(mm)": -0.03,
    "Z(mm)": 0.04,
    "X_Deg" : 0,
    "Y_Deg" : 45,
    "Z_Deg" : 45,

    "batteryInfo": "양호",
    "download": "다운로드"
  },
  {
    "id": "031",
    "type": "변위",
    "location": "Zone A-1",
    "status": "경고",
    "battery": "96%",
    "lastUpdated": "2025-01-20 14:30",
    "X(mm)": 0.12,
    "Y(mm)": -0.03,
    "Z(mm)": 0.04,
    "X_Deg" : 0,
    "Y_Deg" : 45,
    "Z_Deg" : 45,

    "batteryInfo": "양호",
    "download": "다운로드"
  },
  {
    "id": "032",
    "type": "변위",
    "location": "Zone A-1",
    "status": "경고",
    "battery": "96%",
    "lastUpdated": "2025-01-20 14:30",
    "X(mm)": 0.12,
    "Y(mm)": -0.03,
    "Z(mm)": 0.04,
    "X_Deg" : 0,
    "Y_Deg" : 45,
    "Z_Deg" : 45,

    "batteryInfo": "양호",
    "download": "다운로드"
  },
  {
    "id": "033",
    "type": "변위",
    "location": "Zone A-1",
    "status": "경고",
    "battery": "96%",
    "lastUpdated": "2025-01-20 14:30",
    "X(mm)": 0.12,
    "Y(mm)": -0.03,
    "Z(mm)": 0.04,
    "X_Deg" : 0,
    "Y_Deg" : 45,
    "Z_Deg" : 45,

    "batteryInfo": "양호",
    "download": "다운로드"
  },
  {
    "id": "034",
    "type": "변위",
    "location": "Zone A-2",
    "status": "점검",
    "battery": "96%",
    "lastUpdated": "2025-01-20 14:30",
    "X(mm)": 0.12,
    "Y(mm)": -0.03,
    "Z(mm)": 0.04,
    "X_Deg" : 0,
    "Y_Deg" : 45,
    "Z_Deg" : 45,

    "batteryInfo": "양호",
    "download": "다운로드"
  },
  {
    "id": "035",
    "type": "변위",
    "location": "Zone A-2",
    "status": "정상",
    "battery": "96%",
    "lastUpdated": "2025-01-20 14:30",
    "X(mm)": 0.12,
    "Y(mm)": -0.03,
    "Z(mm)": 0.04,
    "X_Deg" : 0,
    "Y_Deg" : 45,
    "Z_Deg" : 45,

    "batteryInfo": "양호",
    "download": "다운로드"
  },
  {
    "id": "036",
    "type": "변위",
    "location": "Zone A-3",
    "status": "점검",
    "battery": "96%",
    "lastUpdated": "2025-01-20 14:30",
    "X(mm)": 0.12,
    "Y(mm)": -0.03,
    "Z(mm)": 0.04,
    "X_Deg" : 0,
    "Y_Deg" : 45,
    "Z_Deg" : 45,

    "batteryInfo": "양호",
    "download": "다운로드"
  },
  {
    "id": "037",
    "type": "변위",
    "location": "Zone A-2",
    "status": "정상",
    "battery": "96%",
    "lastUpdated": "2025-01-20 14:30",
    "X(mm)": 0.12,
    "Y(mm)": -0.03,
    "Z(mm)": 0.04,
    "X_Deg" : 0,
    "Y_Deg" : 45,
    "Z_Deg" : 45,

    "batteryInfo": "양호",
    "download": "다운로드"
  },
  {
    "id": "038",
    "type": "변위",
    "location": "Zone A-3",
    "status": "경고",
    "battery": "96%",
    "lastUpdated": "2025-01-20 14:30",
    "X(mm)": 0.12,
    "Y(mm)": -0.03,
    "Z(mm)": 0.04,
    "X_Deg" : 0,
    "Y_Deg" : 45,
    "Z_Deg" : 45,

    "batteryInfo": "양호",
    "download": "다운로드"
  },
  {
    "id": "039",
    "type": "변위",
    "location": "Zone A-1",
    "status": "정상",
    "battery": "96%",
    "lastUpdated": "2025-01-20 14:30",
    "X(mm)": 0.12,
    "Y(mm)": -0.03,
    "Z(mm)": 0.04,
    "X_Deg" : 0,
    "Y_Deg" : 45,
    "Z_Deg" : 45,

    "batteryInfo": "양호",
    "download": "다운로드"
  },
  {
    "id": "040",
    "type": "변위",
    "location": "Zone A-2",
    "status": "정상",
    "battery": "96%",
    "lastUpdated": "2025-01-20 14:30",
    "X(mm)": 0.12,
    "Y(mm)": -0.03,
    "Z(mm)": 0.04,
    "X_Deg" : 0,
    "Y_Deg" : 45,
    "Z_Deg" : 45,

    "batteryInfo": "양호",
    "download": "다운로드"
  },
  {
    "id": "041",
    "type": "변위",
    "location": "Zone A-3",
    "status": "점검",
    "battery": "96%",
    "lastUpdated": "2025-01-20 14:30",
    "X(mm)": 0.12,
    "Y(mm)": -0.03,
    "Z(mm)": 0.04,
    "X_Deg" : 0,
    "Y_Deg" : 45,
    "Z_Deg" : 45,

    "batteryInfo": "양호",
    "download": "다운로드"
  },
  {
    "id": "042",
    "type": "변위",
    "location": "Zone A-3",
    "status": "점검",
    "battery": "96%",
    "lastUpdated": "2025-01-20 14:30",
    "X(mm)": 0.12,
    "Y(mm)": -0.03,
    "Z(mm)": 0.04,
    "X_Deg" : 0,
    "Y_Deg" : 45,
    "Z_Deg" : 45,

    "batteryInfo": "양호",
    "download": "다운로드"
  },
  {
    "id": "043",
    "type": "변위",
    "location": "Zone A-2",
    "status": "정상",
    "battery": "96%",
    "lastUpdated": "2025-01-20 14:30",
    "X(mm)": 0.12,
    "Y(mm)": -0.03,
    "Z(mm)": 0.04,
    "X_Deg" : 0,
    "Y_Deg" : 45,
    "Z_Deg" : 45,

    "batteryInfo": "양호",
    "download": "다운로드"
  },
  {
    "id": "044",
    "type": "변위",
    "location": "Zone A-2",
    "status": "경고",
    "battery": "96%",
    "lastUpdated": "2025-01-20 14:30",
    "X(mm)": 0.12,
    "Y(mm)": -0.03,
    "Z(mm)": 0.04,
    "X_Deg" : 0,
    "Y_Deg" : 45,
    "Z_Deg" : 45,

    "batteryInfo": "양호",
    "download": "다운로드"
  },
  {
    "id": "045",
    "type": "변위",
    "location": "Zone A-1",
    "status": "정상",
    "battery": "96%",
    "lastUpdated": "2025-01-20 14:30",
    "X(mm)": 0.12,
    "Y(mm)": -0.03,
    "Z(mm)": 0.04,
    "X_Deg" : 0,
    "Y_Deg" : 45,
    "Z_Deg" : 45,

    "batteryInfo": "양호",
    "download": "다운로드"
  },
  {
    "id": "046",
    "type": "변위",
    "location": "Zone A-3",
    "status": "점검",
    "battery": "96%",
    "lastUpdated": "2025-01-20 14:30",
    "X(mm)": 0.12,
    "Y(mm)": -0.03,
    "Z(mm)": 0.04,
    "X_Deg" : 0,
    "Y_Deg" : 45,
    "Z_Deg" : 45,

    "batteryInfo": "양호",
    "download": "다운로드"
  },
  {
    "id": "047",
    "type": "변위",
    "location": "Zone A-1",
    "status": "주의",
    "battery": "96%",
    "lastUpdated": "2025-01-20 14:30",
    "X(mm)": 0.12,
    "Y(mm)": -0.03,
    "Z(mm)": 0.04,
    "X_Deg" : 0,
    "Y_Deg" : 45,
    "Z_Deg" : 45,

    "batteryInfo": "양호",
    "download": "다운로드"
  },
  {
    "id": "048",
    "type": "변위",
    "location": "Zone A-4",
    "status": "경고",
    "battery": "96%",
    "lastUpdated": "2025-01-20 14:30",
    "X(mm)": 0.12,
    "Y(mm)": -0.03,
    "Z(mm)": 0.04,
    "X_Deg" : 0,
    "Y_Deg" : 45,
    "Z_Deg" : 45,

    "batteryInfo": "양호",
    "download": "다운로드"
  },
  {
    "id": "049",
    "type": "변위",
    "location": "Zone A-4",
    "status": "경고",
    "battery": "96%",
    "lastUpdated": "2025-01-20 14:30",
    "X(mm)": 0.12,
    "Y(mm)": -0.03,
    "Z(mm)": 0.04,
    "X_Deg" : 0,
    "Y_Deg" : 45,
    "Z_Deg" : 45,

    "batteryInfo": "양호",
    "download": "다운로드"
  },
  {
    "id": "050",
    "type": "변위",
    "location": "Zone A-1",
    "status": "점검",
    "battery": "96%",
    "lastUpdated": "2025-01-20 14:30",
    "X(mm)": 0.12,
    "Y(mm)": -0.03,
    "Z(mm)": 0.04,
    "X_Deg" : 0,
    "Y_Deg" : 45,
    "Z_Deg" : 45,

    "batteryInfo": "양호",
    "download": "다운로드"
  }
]'''; // ⬅ 여기에 전체 JSON 붙여넣기

    final List<dynamic> decoded = jsonDecode(jsonString);
    _items = decoded.map((e) => IotItem.fromJson(e)).toList();

    notifyListeners();
  }
}
